url: "https://alexiepogue.com"      # Your domain
baseurl: ""                         # Blank = root-level site
title: "Alexie Pogue"               # ✅ Shows up in tab titles (if layout uses it)

permalink: pretty                   # Clean URLs like /about/, /projects/

collections:
  incidents:
    output: true
    permalink: /incidents/:name/
