# Site Identity
title: "Alexie Pogue"
description: "Building AI audit tools for institutional accountability"
url: "https://alexiepogue.com"
baseurl: "" # leave blank for root-level site

# Theme + Styling
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Pretty URLs
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Collections
collections:
  incidents:
    output: true
    permalink: /incidents/:name/
  protocols:
    output: true
    permalink: /projects/:name/

# Defaults for layouts
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Optional: Enable search or social later
# search: true
# social:
#   links:
#     - "https://github.com/apogue"
#     - "https://twitter.com/apogue"
