# Site Identity
title: "Alexie Pogue"
description: "Building an honest record — from data and firsthand accounts"
url: "https://alexiepogue.com"
baseurl: "" # leave blank for root-level site

# Theme + Styling
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Author Profile
author:
  name: "Alexie Pogue"
  avatar: "/assets/images/bio-photo.jpg"  
  bio: "Researcher developing a framework to understand how universities respond to critical incidents."
  location: "Los Angeles, CA"
  links:
  - label: "Email"
    icon: "fas fa-fw fa-envelope-square"
    url: "mailto:alexie.pogue@gmail.com"
  - label: "LinkedIn"
    icon: "fab fa-fw fa-linkedin"
    url: "https://www.linkedin.com/in/alexie-pogue-38204b49/"
  - label: "GitHub"
    icon: "fab fa-fw fa-github-square"
    url: "https://github.com/APogue"
  - label: "Bluesky"
    icon: "fab fa-fw fa-bluesky"
    url: "https://bsky.app/profile/alexiepogue.bsky.social"    
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/alexiepogue"
  - label: "TikTok"
    icon: "fab fa-fw fa-tiktok"
    url: "https://www.tiktok.com/@alexiepogue"

# Pretty URLs
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-last-modified-at

# Collections
collections:
  incidents:
    output: true
    permalink: /incidents/:name/
  protocols:
    output: true
    permalink: /projects/:name/
  interviews:
    output: true
    permalink: /interviews/:name/
  legacy:
    output: true
    permalink: /legacy/:name/
  narrative_framing:
    output: true
    permalink: /narrative_framing/:name/

# Defaults for layouts
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Social Links (for footer and other theme features)
social:
  links:
    - "https://twitter.com/alexiepogue"
    - "https://bsky.app/profile/alexiepogue.bsky.social"
    - "https://www.linkedin.com/in/alexie-pogue-38204b49/"
    - "https://www.tiktok.com/@alexiepogue"

# Optional: Enable search or social later
# search: true