- id: DB-045
  type: Daily Bruin
  date: 2024-04-30
  title: "Police delayed response to encampment attack"
  file: sources/DB-045.txt
  used_in: [INC-001]

- id: ADM-014
  type: Admin Email
  date: 2024-05-01
  title: "Chancellor’s campus-wide statement"
  file: sources/ADM-014.txt
  used_in: [INC-001]
