- id: DB-001
  type: Daily Bruin
  date: 2024-04-02
  title: "Op-ed: Antisemitic imagery at UC Regents meeting protest threatens campus discourse"
  file: sources/DB-001.txt
  url: "https://dailybruin.com/2024/04/02/op-ed-antisemitic-imagery-at-uc-regents-meeting-protest-threatens-campus-discourse"
  used_in: [INC-001]

